### ISSUE TITLE
Ivanivokova

### ISSUE THREAD

**Issue by BigMobos** [jetelain/Arma3Map#101]
Hey there, wondering if we could have the Ivanivokova terrain added. 

https://steamcommunity.com/sharedfiles/filedetails/?id=3316635810

Appreciate all the work y'all do!

**Comment by jetelain** [comment]
Hi,

It's available on https://atlas.plan-ops.fr/maps/arma3/ivanivokova
It will be on maps and ctab in few hours

**Comment by jetelain** [comment]
I've enabled some beta features:
Vector Render with a new map style: https://atlas.plan-ops.fr/maps/arma3/ivanivokova/164?x=11480&y=13172&w=6820&h=3368
PDF Downloads at 1:25000 : https://atlas.plan-ops.fr/maps/arma3/ivanivokova/papermaps
Don't hesitate to report issues on new renders

**Comment by BigMobos** [comment]
Awesome, thanks! Will take a stab at the new features as well and report back if there are any issues. Cheers again!
