### ISSUE TITLE
Arma 3 Dogechnya, Krayina Map Addition

### ISSUE THREAD

**Issue by Raptor0830** [jetelain/Arma3Map#102]
Hello, I would like to kindly ask for the map addition of "Dogechnya" and "Krayina, Ukraine". Dogechnya would be first priority. Thank you all.

**Comment by jetelain** [comment]
Hi, 

Maps have been added to the atlas. It will be available in few hours on maps and ctab.

https://atlas.plan-ops.fr/maps/arma3/gc_krayina
https://atlas.plan-ops.fr/maps/arma3/dogechnya
