### ISSUE TITLE
Map Request: Wild Mountains (Livonia and Tanoa Veg)

### ISSUE THREAD

**Issue by Storey41** [jetelain/Arma3Map#104]
Hello there!

Would it be any trouble to add the following two maps for Wild Mountains?

They are as follows:
- https://steamcommunity.com/workshop/filedetails/?id=2731181579
- https://steamcommunity.com/sharedfiles/filedetails/?id=2650889206

We in the OPTRE (Halo sim) community are immensely grateful for your efforts with PLANOPS and beyond- you're doing God's work here! <3

**Comment by jetelain** [comment]
Hi,
It's available on the atlas, it will be available in few hours on ctab and maps:
https://atlas.plan-ops.fr/maps/arma3/egl_wild
https://atlas.plan-ops.fr/maps/arma3/egl_wild_l

**Comment by Storey41** [comment]
You're a legend! Thank you so much! 😄
