### ISSUE TITLE
[MAP] Deniland

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/Arma3Map#24]
Would it be possible to have Deniland added to https://maps.plan-ops.fr/?
[Workshop link](https://steamcommunity.com/sharedfiles/filedetails/?id=1231955722&searchtext=deniland)

**Comment by jetelain** [comment]
Available on https://mapsdata.plan-ops.fr/deniland.html

The github deployment is broken due to data amount (it times out), I've made an alternative hosting at https://mapsdata.plan-ops.fr/

**Comment by jetelain** [comment]
It may take up to one day to be available on ctab / maps due to cache (CDN cache + Applications cache)
