### ISSUE TITLE
Adding map - Weferlingen

### ISSUE THREAD

**Issue by for** [jetelain/Arma3Map#25]
I was just wondering if it were possible to add the Weferlingen map from Global Mobilisation.
Im part of a millsim group that used plan ops and we are starting up a new campaign on it.

**Comment by jetelain** [comment]
Available on https://mapsdata.plan-ops.fr/gm_weferlingen.html

It may take up to one day to be available on ctab / maps due to cache (CDN cache + Applications cache)

**Comment by for** [comment]
Many thanks and thank you for your continued work on this amazing project!
