### ISSUE TITLE
Request for Map G.O.S Leskovets

### ISSUE THREAD

**Issue by Carlxodown** [jetelain/Arma3Map#28]
We would love to have G.O.S Leskovets on the webpage, its one of the nicest maps in ArmA3 (in our opinion) https://steamcommunity.com/sharedfiles/filedetails/?id=855464203

**Comment by jetelain** [comment]
Available on https://mapsdata.plan-ops.fr/pja314.html

It may take up to one day to be available on ctab / maps due to cache (CDN cache + Applications cache)
