### ISSUE TITLE
Implement Map : North Takistan

### ISSUE THREAD

**Issue by PulsarNeutronStar** [jetelain/Arma3Map#30]
https://steamcommunity.com/sharedfiles/filedetails/?id=2829330653

Thank youuuuuu

**Comment by jetelain** [comment]
Available on https://mapsdata.plan-ops.fr/northtakistan.html

It may take up to one day to be available on ctab / maps due to cache (CDN cache + Applications cache)

**Comment by PulsarNeutronStar** [comment]
we mainly use it for planning pre op.

Amazing thank you!
