### ISSUE TITLE
Map Background Chernarus 2020 is outdated

### ISSUE THREAD

**Issue by ak131554** [jetelain/Arma3Map#31]
First of all, your project is awesome. But, I'm planing a campaign with several missions on the relativly new map Chernarus 2020. I want to include maps of the corresponding operation in the briefings. But the map background for this ArmA3-Map seems to be outdated, especially in the north.

Many towns are missing. One can only see the roads, but neither houses nor town names. I've also found missing markings for rocks. Please have a look to the following comparison between ingame map (taken from editor) and you webapp:

Arma3:
![107410_20220718103639_1](https://user-images.githubusercontent.com/18483274/179477037-85cbe32b-0b30-4494-8724-084ec23822e7.png)

Planops:
![Screenshot 2022-07-18 104439](https://user-images.githubusercontent.com/18483274/179476982-f9a73c61-ee65-404d-92bb-ae49e8af7615.png)

Arma3:
![107410_20220718103523_1](https://user-images.githubusercontent.com/18483274/179477029-71b138d4-0eef-469e-bb36-74b3e0c339b4.png)

Planops:
![Screenshot 2022-07-18 104355](https://user-images.githubusercontent.com/18483274/179476972-448a2a46-2155-40f7-b6b2-075a59564de7.png)

An example of missing rocks you'll see at the quarry north of Severograd. In the ingame map you can see a huge amount of rock markings, but in your Planop maps one can only see contour lines.

Please, provide an updated version of the Chernarus 2020 map background. Please tell me, if I can support you with this task.

**Comment by jetelain** [comment]
Tiles are up to date, https://mapsdata.plan-ops.fr/cup_chernarus_a3.html

It may take up to one day to be available on ctab / maps due to cache (CDN cache + Applications cache)
