### ISSUE TITLE
Add UMB Colombia map

### ISSUE THREAD

**Issue by SzRed** [jetelain/Arma3Map#36]
I'd like to request [UMB Colombia](https://steamcommunity.com/sharedfiles/filedetails/?id=2266710560) map to be added to the Atlas.
It is being used by some of the milsim units, is highly rated, perfect for operations against the cartel.

Currently my unit would like to use it, but our requirement for launching new campaigns is to have map being available on the PLANOPS.

Thank you in advance!

**Comment by jetelain** [comment]
It's done
