### ISSUE TITLE
Bastek

### ISSUE THREAD

**Issue by irkanot** [jetelain/Arma3Map#38]
please con you add BASTEK map from steam workshop?

[https://steamcommunity.com/sharedfiles/filedetails/?id=2684046473&searchtext=bastekx](https://steamcommunity.com/sharedfiles/filedetails/?id=2684046473&searchtext=bastekxxxxxxx)

**Comment by jetelain** [comment]
It's available : https://maps.plan-ops.fr/Atlas/k9s_bastek
