### ISSUE TITLE
Map grid in web view offset from ingame grid on certain maps.

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/Arma3Map#42]
1. Open map in TacMap, e.g. G.O.S N'Djenahoud 
2. Ingame x direction starts at 1 on this map and not zero like shown in TacMap.
3. Y direction grid ingame starts at 0 slightly below the map, this can be seen in TacMap as the grid numbers don't align with the grids itself.
![image](https://user-images.githubusercontent.com/57712666/191987811-14d1c8a8-ca3e-422d-9302-9a4e6fb7b928.png)
Picture illustrates the gap between the `01` y marker and the 01 line on map.

This is probably only affecting a few maps but makes it quite difficult to find spots you've marked in the browser while making the mission in the editor (no access to Ctab there..).

**Comment by jetelain** [comment]
Same as #9

**Comment by jetelain** [comment]
Data update is tracked by https://github.com/jetelain/GameMapStorage.Arma3/issues/3
