### ISSUE TITLE
Uzbin Valley update

### ISSUE THREAD

**Issue by Sgt-Johnson** [jetelain/Arma3Map#43]
Hey if possible could you update the planops for Uzbin Valley? My unit is mid campaign on it and the map updated which changed a lot, we'd love if you could update the planops too. Thank you!

P.S. Thanks for how quickly you guys respond/update/upload!

https://steamcommunity.com/sharedfiles/filedetails/?id=1882424760

**Comment by jetelain** [comment]
Hi, 
Map have been updated : https://maps.plan-ops.fr/Atlas/uzbin
Existing tac maps may be broken because map size has changed.
