### ISSUE TITLE
Fallujah 2.0

### ISSUE THREAD

**Issue by Sgt-Johnson** [jetelain/Arma3Map#52]
Hey I was hoping for Fallujah 2.0 to be added. I'm surprised it hasn't been requested/added already, so I'm expecting there's an issue adding it maybe?

Either way, thanks very much!

https://steamcommunity.com/sharedfiles/filedetails/?id=2926828901

**Comment by jetelain** [comment]
Hi,
It's available : https://maps.plan-ops.fr/Atlas/fallujah
