### ISSUE TITLE
Request for Bala Murghab, Afghanistan to be added

### ISSUE THREAD

**Issue by MlijecniCovjek** [jetelain/Arma3Map#54]
https://steamcommunity.com/sharedfiles/filedetails/?id=2781043850

Hello, my request is for Bala Murghab to be added to the PLANOPS website as I am looking to use it for a campaign within the unit named UNITAF

**Comment by jetelain** [comment]
Hi,
It's available: https://maps.plan-ops.fr/Atlas/bala_murghab_summer
