### ISSUE TITLE
"The Bra"

### ISSUE THREAD

**Issue by Sgt-Johnson** [jetelain/Arma3Map#57]
Hey thanks for implementing all my previous requests, just hoped to get "The Bra" added from the Prairie Fire DLC. 

Wiki link for clarity - https://armedassault.fandom.com/wiki/The_Bra_(terrain)

Cheers!

**Comment by jetelain** [comment]
Hi, it's available : https://maps.plan-ops.fr/Atlas/vn_the_bra
