### ISSUE TITLE
Map Requests

### ISSUE THREAD

**Issue by Frank-Jager** [jetelain/Arma3Map#59]
Hi folks, any chance of adding in the Mutambara, RKSL Bovington, and RKSL BATUS Maps please?

https://steamcommunity.com/sharedfiles/filedetails/?id=2814015609&searchtext=Mutambara

https://steamcommunity.com/sharedfiles/filedetails/?id=2255211315&searchtext=bovington

https://steamcommunity.com/sharedfiles/filedetails/?id=2863099235&searchtext=BATUS%23

**Comment by jetelain** [comment]
Hi, It's available :
https://maps.plan-ops.fr/Atlas/rksla3_t_bov_test_area
https://maps.plan-ops.fr/Atlas/ukaf_batus
https://maps.plan-ops.fr/Atlas/swu_public_rhode_map
