### ISSUE TITLE
Exporting maps

### ISSUE THREAD

**Issue by ArmedVeteran** [jetelain/Arma3Map#7]
Hey! I've just recently stumbled upon your work and I have to say it's simply amazing. cTab IRL is mindblowing to me. I'd really love to help you with exporting more terrains to Arma3Map, so that the mod would have even more potential, if you're interested. Let me know what you think ;)

**Comment by jetelain** [comment]
Hello!
Exporting a map is a partially a manual operation, you have to adjust a lot of parameters, I think I can build an extension to automate much more the process to allow you to help exporting maps. I will try to work on it in the following days.

**Comment by ArmedVeteran** [comment]
> Hello!
> Exporting a map is a partially a manual operation, you have to adjust a lot of parameters, I think I can build an extension to automate much more the process to allow you to help exporting maps. I will try to work on it in the following days.

Great! Looking forward to it :D

**Comment by jetelain** [comment]
Hi,
I've build an extension to fully automate the process, see https://github.com/jetelain/Arma3Map/blob/master/HowToExport.md on how to use it.
Exporting a map will take some minutes (compared to the previous process that took 1 to 2 hours for each map).
I've tested it only on base game maps, it might need some additional work for mods maps.

**Comment by ArmedVeteran** [comment]
I'll test it out as soon as I can, thank you :)
