### ISSUE TITLE
Possible maps to add

### ISSUE THREAD

**Issue by DeadEcho1B** [jetelain/Arma3Map#73]
Hello, I came across your website for the Planops maps and would like to thank you for what you've done! I started implementing it into our Arma campaign for use as an intel board and it has been a huge help. I was wondering if it was possible to get these two maps added, we will be going to them later and it would be amazing if we could continue to use your website for future use!

https://steamcommunity.com/sharedfiles/filedetails/?id=3043043427
https://steamcommunity.com/sharedfiles/filedetails/?id=3013515917

Thank you for your time!

**Comment by jetelain** [comment]
Hi, It's available:
https://maps.plan-ops.fr/Atlas/vtf_lybor
https://maps.plan-ops.fr/Atlas/vtf_korsac
