### ISSUE TITLE
Song Bin Tan 2.0 (Apex)

### ISSUE THREAD

**Issue by DeadEcho1B** [jetelain/Arma3Map#87]
Hey! Would love to have this map on here to round out the G.O.S. Maps!

https://steamcommunity.com/sharedfiles/filedetails/?id=878119643

**Comment by jetelain** [comment]
Hi, It's available on the new atlas https://atlas.plan-ops.fr/maps/arma3/pja312. It will be available on ctab and maps in few hours.
