### ISSUE TITLE
New Maps: Operation TREBUCHET

### ISSUE THREAD

**Issue by Storey41** [jetelain/Arma3Map#88]
Hello!

It would be wonderful to have the maps from Operation TREBUCHET and Operation TREBUCHET: First Contact in PLANOPS for the benefit of Halo sim communities worldwide.

I'm part of the development team for Operation: TREBUCHET, so if there is anything I can do or learn to help implement these maps, please let me know!

Thanks! 
- Storey

Base OPTRE maps (https://steamcommunity.com/sharedfiles/filedetails/?id=769440155): 
- [x] - Madrigal
- [x] - Blood Gulch
- [x] - Iberius
- [x] - Kholo

Lower priority base OPTRE maps (https://steamcommunity.com/sharedfiles/filedetails/?id=769440155): 
- [x] - Eridanus Secundus
- [x] - Gridlock
- [x] - Phobos
- [x] - Sandstorm
- [x] - Harvest (still heavy WIP, may be best left out)

First Contact maps (https://steamcommunity.com/sharedfiles/filedetails/?id=1572627279): 

- [x] - IO4: Highlands
- [x] - IO4: Coldlands
- [x] - IO4: Wetlands
- [x] - IO4: Archipelago

**Comment by jetelain** [comment]
Hi, maps are being processed into the new atlas except Sandstorm (the map is too small, export procedure fails).
I still have to set metadata workshop links and screenshots.
It will be available on maps and ctab in few hours.

**Comment by jetelain** [comment]
Maps are available on maps and ctab. I keep the issue open for Sandstorm, I need to rework the export script.

**Comment by jetelain** [comment]
Hi, I finally managed to add Standstorm : https://atlas.plan-ops.fr/maps/arma3/optre_sandstorm
