### ISSUE TITLE
NEW MAP 

### ISSUE THREAD

**Issue by DocHoliday97** [jetelain/Arma3Map#89]
requesting the new map block island for the plans ops websight, 
Thanks

https://steamcommunity.com/sharedfiles/filedetails/?id=3246616107

**Comment by jetelain** [comment]
Hi, maps are being processed into the new atlas. I have still have to set metadata : workshop link and screenshot.
It will be available on maps and ctab in few hours.

**Comment by jetelain** [comment]
Hi it's available on atlas, maps and ctab:

https://atlas.plan-ops.fr/maps/arma3/gallo_blockisland
https://maps.plan-ops.fr/Atlas/gallo_blockisland
