### ISSUE TITLE
Map with incorrect coordinates

### ISSUE THREAD

**Issue by jetelain** [jetelain/Arma3Map#9]
Some maps have incorrect coordinates (map grid does not match computed grid), it requires somes investigation:
- Aliabad Region 
- Esseker 
- Everon 
- G.O.S Dariyah
- G.O.S N'Djenahoud
- G.O.S N'Ziwasogo
- Hazar-Kot Valley
- Hindukush 
- Rosche, Germany (2.0)

0000-0000 coordinates does not seems to be bottom left, but top right or might be shifted

**Comment by jetelain** [comment]
In fact map coordinates does not match grid coordinates. So we need to extra informations to give the transformation between the two coordinates systems, and change how thé scripts displays coordinates and graticule.

**Comment by ianespana** [comment]
From some testing I've done, the X and Y values need to be swapped around when placing markers so they correctly point to in-game locations.
This can be tested by putting a marker on (0,100) or (100,0) and then placing an object in game with the same coordinates. You'll see the axes are swapped around

**Comment by jetelain** [comment]
Data update is tracked by https://github.com/jetelain/GameMapStorage.Arma3/issues/3
