### ISSUE TITLE
New Maps: Global Ops Terrain

### ISSUE THREAD

**Issue by Faosmaster6151** [jetelain/Arma3Map#90]
Hey there!

First I want to say I absolutely love what you all have done with the detail put into Planops and the effort you put in. But I would love to see Global Ops Terrain's added into your map collection. It's a three map collection that I'm looking to create op boards for. I understand the effort that would be needed so I can understand if your unable/unwilling to do so. But I leave that to you all if you decide to pursue this.

Map Link: https://steamcommunity.com/sharedfiles/filedetails/?id=2917444360&searchtext=global+ops

Thanks!

- Faos

**Comment by jetelain** [comment]
Hi,

It's available on the new atlas and on maps. It may takes some hours to be available on ctab.

https://atlas.plan-ops.fr/maps/arma3/go_map_fjord
https://atlas.plan-ops.fr/maps/arma3/islapera
https://atlas.plan-ops.fr/maps/arma3/farabad

https://maps.plan-ops.fr/Atlas/go_map_fjord
https://maps.plan-ops.fr/Atlas/islapera
https://maps.plan-ops.fr/Atlas/farabad

**Comment by Faosmaster6151** [comment]
Thank you! This is honestly great stuff from you guys. I appreciate it deeply, Especially the effort you've put in with this. Again thank you.
