### ISSUE TITLE
Request for the map "Cham"

### ISSUE THREAD

**Issue by AFelske** [jetelain/Arma3Map#95]
Hello,

I wanted to ask, if you could add the map "Cham" (https://steamcommunity.com/sharedfiles/filedetails/?id=1789554117&searchtext=cham) to plan-ops. 

Size of the map: 8 x 8 km
Requirement: Global Mobilization or Global Mobilization DLC Compatibility Data for Non-Owners

I'm building a mission on the map and it's not in plan-ops, that's why I wanted to ask.

Best regards,
Artur

**Comment by jetelain** [comment]
Hi,
It's available on the new atlas https://atlas.plan-ops.fr/maps/arma3/tem_cham
It will be available in few hours on maps and ctab

**Comment by AFelske** [comment]
Thank you.
